{application,waychat,
             [{description,"Chat System"},
              {vsn,"1.0"},
              {registered,[]},
              {applications,[kernel,stdlib,mnesia]},
              {mod,{waychat_app,[]}},
              {env,[]},
              {modules,[server_util,waychat_app,waychat_gateway,
                        waychat_gateway_sup,waychat_room,
                        waychat_room_register,waychat_room_sup,waychat_sup,
                        waychat_user]}]}.
